KupiProdai/urls.py
from django.contrib import admin
from django.urls import path,include
from Main import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.main_page),
    path('ad/<int:pk>/', views.ad_detail,name='ad_detail'),
    path('cart/',include('cart.urls',namespace='cart')),
    path('login', views.login_view,name='login'),
    path('register',views.register_view,name='register'),
    path('logout/',views.logout_view,name='logout'),
    path('product_list/',views.product_list_view,name='product_list'),
    path('product_add',views.product_add_view)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('ad/<int:pk>/', views.ad_detail,name='ad_detail'),
    path('cart/',include('cart.urls',namespace='cart')),
    path('login', views.login_view,name='login'),
    path('register',views.register_view,name='register'),
    path('logout/',views.logout_view,name='logout'),
    path('product_list/',views.product_list_view,name='product_list'),
    path('product_add',views.product_add_view),
    path('new',views.new_view),
    path('',views.main_page)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('^$', views.cart_detail, name='cart_detail'),
    path('^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path('^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField( )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.views.decorators.http import require_POST
from Main.models import Ad
from .cart import Cart
from .forms import CartAddProductForm
from django.shortcuts import render, redirect, get_object_or_404


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Ad, id=product_id)
    form = CartAddProductForm(request.POST)
    print(form.errors)
    if form.is_valid():
        cd = form.cleaned_data
        print(cd)
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Ad, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends "asserts/html/base.html" %}
{% load static %}
{% block css %}
    <link  type="text/css" rel="stylesheet" href="{% static 'cart/detail.css' %}">
{% endblock %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img class="image" src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.header }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id%}">Remove</a></td>
                    <td class="num">{{ item.price }}тг.</td>
                    <td class="num">{{ item.total_price }}тг.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}тг.</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="" class="button light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock %}