KupiProdai/urls.py
from django.contrib import admin
from django.urls import path,include
from Main import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.main_page),
    path('ad/<int:pk>/', views.ad_detail,name='ad_detail'),
    path('cart/',include('cart.urls',namespace='cart')),
    path('login', views.login_view,name='login'),
    path('register',views.register_view,name='register'),
    path('logout/',views.logout_view,name='logout'),
    path('product_list/',views.product_list_view,name='product_list'),
    path('product_add',views.product_add_view)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('ad/<int:pk>/', views.ad_detail,name='ad_detail'),
    path('cart/',include('cart.urls',namespace='cart')),
    path('login', views.login_view,name='login'),
    path('register',views.register_view,name='register'),
    path('logout/',views.logout_view,name='logout'),
    path('product_list/',views.product_list_view,name='product_list'),
    path('product_add',views.product_add_view),
    path('new',views.new_view),
    path('',views.main_page)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('^$', views.cart_detail, name='cart_detail'),
    path('^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path('^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

templates/asserts/html/Product_Ad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="" method="post">
    {% csrf_token %}
    <p>{{ form.header }}</p>
    <p>{{ form.category }}</p>
    <p>{{ form.city }}</p>
    <p>{{ form.description }}</p>
    <p>{{ form.price }}</p>
    <input type="submit" value="Разместить">
</form>

</body>
</html>

templates/asserts/html/ad.html
{% extends 'asserts/html/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ header }}
{% endblock %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static 'asserts/css/product.css' %}"  >
{% endblock %}




{% block content %}

    <img src="{{ image}}">


    {{ header }}
    <p>{{ city}}</p>

<br>
{{ category }}
<br>
{{ price }}
<br>
{{ description }}
    {{ views }}

    <form action=" {% if user.is_authenticated %}
                        {% url "cart:cart_add" product_id=id %}
                    {% else %}
                        {% url 'login' %}
                    {% endif %}
" method="post">
    {% csrf_token %}
        {{ card_add.quantity  }}

    <button type="submit">Добавить в корзину</button>
    </form>
{% endblock %}

templates/asserts/html/base.html
{% load  static %}
<!DOCTYPE html>

<html lang="ru">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        {% block css %}{% endblock %}
        <link href="https://fonts.googleapis.com/css?family=Didact+Gothic&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'asserts/css/base.css' %}">
    </head>
    <body >
        <header>
            <div class="header">
                <a href="/new" class="logo-box"><img src="{% static 'asserts/imgs/logo.png' %}" class="logo" alt="logo">
</a>
                <form class="search-form" action="{% url 'product_list' %}" method="get">

                    <input class="search" name="name" type="search" placeholder="Поиск . . .">
                    <input type="submit" class="search-btn" value="Найти">
                </form>
                <button id="colopser" class="menu" onclick="barFunction(this)"></button>
                <div id="menu-links" class="menu-links">
                    <a class="cart" href="{% url 'cart:cart_detail' %}">Корзина</a>
                    <a class="profile" href=""> Мой профиль</a>
                </div>
                <a class="cart" href="{% url 'cart:cart_detail' %}">Корзина</a>
                <a class="profile" href="{% url 'login' %}">Мой профиль</a>

            </div>
        </header>
        {% block content %}{% endblock %}

    </body>
</html>

templates/asserts/html/index.html
{% extends 'asserts/html/base.html' %}
{% load static %}
{% block css %}
    <link  type="text/css" rel="stylesheet" href="{% static 'asserts/css/index.css' %}">
{% endblock %}
{% block content %}
  <div class="content">
      <div class="seacrh-box">
          <br>
        <div class="search">
          <input id="search-input" type="text" placeholder="Искать среди 3 234 232 объявлений ... ">
          <input id="search-cat">
          <button id="search-btn">Поиск</button>
      </div>
      </div>
      <div class="category-box">
        <div class="category">
            <form action="{% url 'product_list' %}" method="get">
                <div class="mobile-ctg">
                    <input class="input" type="submit" name="filter" value="Мобильные/Смартфоны" >
                </div>
              <div class="comp-ctg">
                  <input class="input" type="submit" name="filter" value="Компьютеры/Ноутбуки" >
              </div>
              <div class="jellewry-ctg">
                  <input class="input" type="submit" name="filter" value="Украшения/Бижутерия" >
              </div>
              <div class="shoes-ctg">
                  <input class="input" type="submit" name="filter" value="Обувь" >
              </div>
              <div class="tv-ctg">
                  <input class="input" type="submit" name="filter" value="Телевизоры" >
              </div>
              <div class="audio-ctg">
                  <input class="input" type="submit" name="filter" value="Аудио/Видео" >
              </div>
            </form>

      </div>
      </div>

      <div class="top">
          <p><label class="top-text">Популярные товары</label></p>
          <div class="top-products">
              {% for i in ads %}
                  <a href="{% url 'ad_detail' pk=i.pk %}">
                <div class="product">

                  <img src="{{ i.image }}">
                  <p>{{ i.description }}<br></p>
                  <div class="buy">
                       <label class="price"><b>{{ i.price}}тг.</b></label>

                  </div>

                  </div>
                  </a>
              {% endfor %}

          </div>
      </div>
  </div>
{% endblock %}

templates/asserts/html/login.html
{% extends 'asserts/html/base.html' %}
{% load static %}
{% block title %}
    Login
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'asserts/css/login.css' %}">
{% endblock %}
{% block content %}
    <div class="login">
    <p>Login</p>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.username }}
            {{ form.password }}
            <input type="submit" value="Войти" >
        </form>
    <a href="{% url 'register' %}">Зарегистрироваться!</a>
    </div>

{% endblock %}

templates/asserts/html/new.html
{% load  static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'asserts/js/slick/slick-theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'asserts/js/slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'asserts/css/new.css' %}">
</head>
<body >
    <header>
        <div class="header">
<a class="logo-box" href="/new"><img src="{% static 'asserts/imgs/logo.png' %}" class="logo" alt="logo">
</a>            <form class="search-form" action="{% url 'product_list' %}" method="get">

                <input class="search" name="name" type="search" placeholder="Поиск . . .">
                <input type="submit" class="search-btn" value="Найти">
            </form>
            <button id="colopser" class="menu" onclick="barFunction(this)"></button>
            <div id="menu-links" class="menu-links">
                <a class="cart" href="{% url 'cart:cart_detail' %}">Корзина</a>
                <a class="profile" href=""> Мой профиль</a>
            </div>
            <a class="cart" href="{% url 'cart:cart_detail' %}">Корзина</a>
            <a class="profile" href="{% url 'login' %}">Мой профиль</a>

        </div>
    </header>

    <section class="top-content">
        <div class="top-content-box">
            <div class="category-list">
            <div class="category-name">
                    Категории
            </div>
            <form action="{% url 'product_list' %}" class="form-ctg" method="get">
                <div class="mobile">
                    <input class="mobile-ctg" type="submit" name="category" value="Мобильные/Смартфоны" >
                </div>
              <div class="comp">
                  <input class="pc-ctg" type="submit" name="category" value="Компьютеры/Ноутбуки" >
              </div>
              <div class="jellewry">
                  <input class="jellewry-ctg" type="submit" name="category" value="Украшения/Бижутерия" >
              </div>
              <div class="shoes">
                  <input class="shoes-ctg" type="submit" name="category" value="Обувь" >
              </div>
              <div class="tv">
                  <input class="tv-ctg" type="submit" name="category" value="Телевизоры" >
              </div>
              <div class="audio">
                  <input class="audio-ctg" type="submit" name="category" value="Аудио/Видео" >
              </div>
            </form>
        </div>
            <div class="content-box">
                <div id="slider">

                    <div id="slider-box">
                        <div class="slides showing" ><img src="{% static 'asserts/imgs/img3.jpg' %}" alt=""></div>
                        <div class="slides" ><img src="{% static 'asserts/imgs/img2.jpg' %}" alt=""></div>
                    </div>


                    <button id="btn-left" onclick="">&#10094;</button>
                    <button id="btn-right" onclick="">&#10095;</button>
                </div>

            </div>
        </div>

        <div class="top">Популярные товары</div>
            <div class="top-products">
                {% for product in products %}
                    <a class="product-link" href=" {% url 'ad_detail' pk=product.pk %}">
                        <div class="product">

                            <div class="product-img"><img src="{{ product.image.url }}" alt=""></div>
                            <div class="product-name"><p>{{ product.header }}</p></div>
                            <div class="price">
                                <form class="price-form" action="{% url 'cart:cart_add' product_id=product.id  %}" method="post">
                                    {% csrf_token %}
                                    {{ cart_add_form.quantity }}
                                    <button class="cart-btn" type="submit">В корзину</button>
                                </form>
                                <div class="price-price">{{ product.price }} тг.</div>

                            </div>
                        </div>
                    </a>

                {% endfor %}


            </div>
    </section>
    <div class="top after">
        Электроника
    </div>
    <section class="after-content">
                {% for product in notebooks_phones %}
                    <a class="product-link" href=" {% url 'ad_detail' pk=product.pk %}">
                        <div class="product">

                            <div class="product-img"><img src="{{ product.image.url }}" alt=""></div>
                            <div class="product-name"><p>{{ product.header }}</p></div>
                            <div class="price">
                                <form class="price-form" action="{% url 'cart:cart_add' product_id=product.id  %}" method="post">
                                    {% csrf_token %}
                                    {{ cart_add_form.quantity }}
                                    <button class="cart-btn" type="submit">В корзину</button>
                                </form>
                                <div class="price-price">{{ product.price }} тг.</div>

                            </div>
                        </div>
                    </a>

                {% endfor %}





    </section>

    <div class="info">
        <div class="info-box">
            <div class="container">
                <div class="icon">
                    <img src="{% static 'asserts/imgs/1.png' %}">
                    <p>100% безопасные платежи</p>
                </div>
            </div>
            <div class="container">
                <div class="icon">
                    <img src="{% static 'asserts/imgs/2.png' %}">
                    <p>100% возврат средств</p>
                </div>
            </div>
            <div class="container">
                <div class="icon">
                    <img src="{% static 'asserts/imgs/3.png' %}">
                    <p>24/7 онлайн-поддержка</p>
                </div>
            </div>
            <div class="container">
                <div class="icon">
                    <img src="{% static 'asserts/imgs/4.png' %}">
                    <p>Удобное мобильное приложение</p>
                </div>
            </div>
        </div>


    </div>

    <footer>
        <div class="footer">

            <div class="payments">
                <p>Варианты платежей</p>
                <img class="payments-icon" src="{% static 'asserts/imgs/payments.png' %}">

            </div>
            <div class="subscribe">
                <p>Подпишитесь на рассылку!</p>
                <form class="email-form" action="" method="post">
                    <input type="text" class="email" placeholder="Ваш e-mail...">
                    <button class="email-btn" type="submit">Отправить!</button>
                </form>
            </div>

        </div>
        <div class="contacts">
                <div class="contact-numbers">Контактные номера:  321 334, +77751840677.</div>
                <div class="contact-address">Контактный адрес: Алматинская область, Каскелен, Университет Сулеймана Демиреля.</div>
                <div class="copyright">Copyright @2019, KupiProdai Private Limited, All rights Reserved</div>
            </div>
    </footer>
    <script src="{% static 'asserts/js/slick/jquery.js' %}"></script>
    <script src="{% static 'asserts/js/slick/slick.min.js' %}"></script>
</body>
   <script src="{% static 'asserts/js/scripts.js' %}">
    </script>
</html>

templates/asserts/html/product_list.html
{% extends 'asserts/html/base.html' %}
{% load static %}
{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static 'asserts/css/product_list.css' %}">
{% endblock %}
{% block content %}




    <section class="main-section">
    <div class="product_list">
        <div class="product-content">
            {% if products %}
                {% for product in products %}
                       <a class="product-link" href=" {% url 'ad_detail' pk=product.pk %}">
                        <div class="product">

                            <div class="product-img"><img src="{{ product.image.url }}" alt=""></div>
                            <div class="product-name"><p>{{ product.header }}</p></div>
                            <div class="price">
                                <form class="price-form" action="{% url 'cart:cart_add' product_id=product.id  %}" method="post">
                                    {% csrf_token %}
                                    {{ cart_add_form.quantity }}
                                    <button class="cart-btn" type="submit">В корзину</button>
                                </form>
                                <div class="price-price">{{ product.price }} тг.</div>

                            </div>
                        </div>
                    </a>

                {% endfor %}
                </div>

            {% else %}
                <p>По вашему запросу товаров не найдено :(</p>
            {% endif %}
        </div>


    </div>
    <div class="search-block">



    </div>
    </section>



{% endblock %}

templates/asserts/html/profile.html
{% extends 'asserts/html/base.html' %}
{% block content %}
    <h1>Profile</h1>
    <p>{{ user.username }}</p>
    <p>{{ user.date_joined }}</p>
    <p>{{ user.user_permissions }}</p>
    <p>{{ user.has_perms }}</p>
    <a href="{% url 'logout' %}"><em>Выйти</em></a>
{% endblock %}

templates/asserts/html/signup.html
{% extends 'asserts/html/base.html' %}
{% load  static %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}